### ISSUE TITLE
Disable Boot Animation causes GSI ROM Bootloop

### ISSUE THREAD

**Issue by Scott-Nx** [JosFlix7/LowRAM-Flag#1]
When the boot animation is disabled using the `debug.sf.nobootanimation=1` property in the `system.prop` file, GSI ROMs enter a bootloop.

**Steps to Reproduce:**
1. Install the JosFlix7/LowRAM-Flag-Plus Magisk module on a GSI ROM.
2. Reboot the device.

**Expected Behavior:**
The device should boot normally without displaying the boot animation.

**Actual Behavior:**
The device enters a bootloop and fails to boot successfully.

**Potential Workaround:**
As a temporary fix, you can remove or comment out the line `debug.sf.nobootanimation=1` in the `system.prop` file. This will re-enable the boot animation and may allow the device to boot normally.

#### As a fix, may be create new branch for GSI ROM that remove `debug.sf.nobootanimation=1` in the `system.prop`

**Relevant File:**
[system.prop](https://github.com/JosFlix7/LowRAM-Flag-Plus/blob/Android-Go-Tweaks/system.prop)

**Comment by JosFlix7** [comment]
Sorry for the delay, I also noticed this bug recently in Custom ROMs of my old Hanoip, so I have decided to remove this prop (marked as comment).
